repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [ --unsafe ]
      - id: end-of-file-fixer
        files: '\.pyi?$'
      - id: trailing-whitespace
        files: '\.pyi?$'
      - id: check-ast
        files: '\.pyi?$'
      - id: check-builtin-literals
        files: '\.pyi?$'
      - id: detect-private-key
        files: '\.pyi?$'
      - id: check-case-conflict
        files: '\.pyi?$'
      - id: pretty-format-json
        files: '\.pyi?$'
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length=120"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config, ./.flake8]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.39.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ push, post-commit ]
